services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - ./data/:/app/var/
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - internal

  web:
    build:
      context: .
      dockerfile: web/backend/Dockerfile
    volumes:
      - ./data/:/app/var/
      - ./.env:/app/.env
    ports:
      - "8080:3100"
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge